apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-agent
  labels:
    app: {{ .Release.Name }}-agent
    type: mcp-client
spec:
  type: {{ .Values.service.agent.type }}
  ports:
    - port: {{ .Values.service.agent.port }}
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}-agent
