apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Release.Name }}-secrets
stringData:
  postgres_password: "{{ randAlphaNum 16 }}"
  anthropic_key: "{{ required "secrets.anthropic_key is required" .Values.secrets.anthropic_key }}"
  descope_project_id: "{{ .Values.secrets.descope_project_id }}"

  fastagent.config.yaml: |
    default_model: haiku
    logger:
      level: "debug"
      type: "console"
      progress_display: false
      show_chat: true
      show_tools: true
      otel:
        enabled: true
        console_debug: true
    mcp:
        servers:
          {{- range $index, $server := .Values.mcpServers }}
            {{ $server.name | replace "-" "_" }}:
              transport: sse
              url: "http://{{ if $server.host }}{{ $server.host }}{{ else }}{{ $server.name }}:8000{{ end }}/sse"
              read_timeout_seconds: 65534
              read_transport_sse_timeout_seconds: 65534
          {{- end }}
