apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-agent
  labels:
    app: {{ .Release.Name }}-agent
    type: mcp-client
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-agent
      type: mcp-client
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-agent
        type: mcp-client
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        {{- with .Values.apex.enabled }}
        - name: wait-for-apex
          image: curlimages/curl:latest
          imagePullPolicy: Always
          command:
            - sh
            - -c
            - |
              URL="http://localhost:12442/healthz/egress"
              while true; do
                echo "Checking $URL..."
                if curl --fail-with-body --silent --show-error --max-time 5 "$URL"; then
                  echo
                  echo "Apex is healthy for egress!"
                  echo
                  break
                else
                  echo
                  echo "Apex is not healthy for egress yet, retrying..."
                  echo
                  sleep 1
                fi
              done
              URL="http://localhost:12442/healthz/ingress"
              while true; do
                echo "Checking $URL..."
                if curl --fail-with-body --silent --show-error --max-time 5 "$URL"; then
                  echo
                  echo "Apex is healthy for ingress!"
                  echo
                  break
                else
                  echo
                  echo "Apex is not healthy for ingress yet, retrying..."
                  echo
                  sleep 1
                fi
              done
        {{- end }}
        - name: db-migrations
          image: "acuvity/acuvity-chatbot-agent:latest"
          imagePullPolicy: Always
          command:
            - /bin/bash
            - -c
            - |
              alembic upgrade head
              if [ $? -ne 0 ]; then
                echo "Database migrations failed. Exiting."
                exit 1
              fi
              echo "Database migrations completed successfully."
          env:
          - name: POSTGRES_SERVER
            value: "{{ .Release.Name }}-postgres"
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            value: postgres
          - name: POSTGRES_DB
            value: chat_db
          - name: ENVIRONMENT
            value: "development"
      containers:
        - name: agent
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "acuvity/acuvity-chatbot-agent:latest"
          imagePullPolicy: Always
          command:
            - /bin/bash
            - -c
            - "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /config/fastagent.config.yaml
              subPath: fastagent.config.yaml
              readOnly: true
            - name: custom-ca
              mountPath: "/etc/ssl/certs/custom"
              readOnly: true
          env:
          - name: POSTGRES_SERVER
            value: {{ .Release.Name }}-postgres
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            value: postgres
          - name: POSTGRES_DB
            value: chat_db
          - name: ENVIRONMENT
            value: "development"
          - name: ACCESS_TOKEN_SECURITY_KEY
            value: "your-secret-key-change-this"
          - name: ACCESS_TOKEN_EXPIRE_MINUTES
            value: "10080"
          - name: BACKEND_CORS_ORIGINS
            value: '["http://localhost:3000","http://localhost:8000"]'
          - name: ANTHROPIC_API_KEY
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-secrets
                key: anthropic_key
          - name: AGENTIC_CONFIG_PATH
            value: "/config/fastagent.config.yaml"

          {{- with .Values.apex.enabled }}
          - name: REQUESTS_CA_BUNDLE # python requests module
            value: /etc/ssl/certs/custom/ca-bundle.crt
          - name: SSL_CERT_FILE # python httpx module
            value: /etc/ssl/certs/custom/ca-bundle.crt
          {{- end }}
          - name: DESCOPE_PROJECT_ID
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-secrets
                key: descope_project_id
      volumes:
        - name: config
          secret:
            secretName: {{ .Release.Name }}-secrets
        - name: custom-ca
          configMap:
            name: acuvity-ca-bundle
            optional: {{ not .Values.apex.enabled }}
