services:
  ui:
    image: acuvity/acuvity-chatbot-ui:latest
    ports:
      - "3000:3000"
    depends_on:
      - agent
    env_file:
      - .env
    environment:
      - REACT_APP_API_SERVER_BASE_URL=http://127.0.0.1:8000/api/v1/chat
      - REACT_APP_DESCOPE_PROJECT_ID=${DESCOPE_PROJECT_ID}
    restart: always

  agent:
    image: acuvity/acuvity-chatbot-agent:latest
    ports:
      - "8000:8000"
    volumes:
      - ../../src/agent/config:/config
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - AGENT_CONFIG_PATH=/config/fastagent.config.yaml
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - DESCOPE_PROJECT_ID=${DESCOPE_PROJECT_ID}
    restart: always

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  mcp-server-fetch:
    image: acuvity/mcp-server-fetch:latest
    env_file:
      - .env
    environment:
      - MINIBRIDGE_LOG_LEVEL=${MCP_SERVER_LOG_LEVEL}
    restart: always

  # mcp-server-brave-search:
  #   image: acuvity/mcp-server-brave-search:latest
  #   env_file:
  #     - .env
  #   environment:
  #     - BRAVE_API_KEY=${BRAVE_API_KEY}
  #     - MINIBRIDGE_LOG_LEVEL=${MCP_SERVER_LOG_LEVEL}
  #   restart: always

  # mcp-server-github:
  #   image: acuvity/mcp-server-github:latest
  #   env_file:
  #     - .env
  #   environment:
  #     - GITHUB_PERSONAL_ACCESS_TOKEN=${GITHUB_PERSONAL_ACCESS_TOKEN}
  #     - MINIBRIDGE_LOG_LEVEL=${MCP_SERVER_LOG_LEVEL}
  #   restart: always

  mcp-server-sequential-thinking:
    image: acuvity/mcp-server-sequential-thinking:latest
    env_file:
      - .env
    environment:
      - MINIBRIDGE_LOG_LEVEL=${MCP_SERVER_LOG_LEVEL}
    restart: always

  mcp-server-memory:
    image: acuvity/mcp-server-memory:latest
    volumes:
      - memory_data:/data
    env_file:
      - .env
    environment:
      - MINIBRIDGE_LOG_LEVEL=${MCP_SERVER_LOG_LEVEL}
    restart: always

  # mcp-server-microsoft:
  #   image: acuvity/mcp-server-microsoft-graph:latest
  #   env_file:
  #     - .env
  #   environment:
  #     - MINIBRIDGE_LOG_LEVEL=${MCP_SERVER_LOG_LEVEL}
  #     - MCP_SERVER_MICROSOFT_GRAPH_TRANSPORT=sse
  #     - MCP_SERVER_MICROSOFT_GRAPH_SERVICE_NAME=mcp-server-microsoft
  #     - MCP_SERVER_MICROSOFT_GRAPH_TENANT_ID=${MCP_SERVER_MICROSOFT_GRAPH_TENANT_ID}
  #     - MCP_SERVER_MICROSOFT_GRAPH_CLIENT_ID=${MCP_SERVER_MICROSOFT_GRAPH_CLIENT_ID}
  #     - MCP_SERVER_MICROSOFT_GRAPH_CLIENT_SECRET=${MCP_SERVER_MICROSOFT_GRAPH_CLIENT_SECRET}
  #   restart: always

volumes:
  postgres_data:
  memory_data:
