services:
  ui:
    volumes:
      - ../../certs/ca-root-cert.pem:/certs/ca-root-cert.pem
    depends_on:
      - agent
    env_file:
      - .env
    environment:
      - REACT_APP_API_SERVER_BASE_URL=https://127.0.0.1:8000/api/v1/chat
      - NODE_EXTRA_CA_CERTS=/certs/ca-root-cert.pem
    restart: always

  agent:
    volumes:
      - ../../certs:/certs
    env_file:
      - .env
    environment:
      - AGENT_CONFIG_PATH=/config/fastagent.tlsconfig.yaml
      - AGENT_TLS_CAFILE=/certs/ca-root-cert.pem
      - AGENT_TLS_SERVER_ENABLE=true
      - AGENT_TLS_SERVER_CERT=/certs/mcp-chatbot-agent-cert.pem
      - AGENT_TLS_SERVER_KEY=/certs/mcp-chatbot-agent-key.pem
    restart: always

  db:

  mcp-server-fetch:
    env_file:
      - .env
    volumes:
      - ../../certs:/certs
    environment:
      - MINIBRIDGE_TLS_SERVER_CERT=/certs/mcp-server-fetch-cert.pem
      - MINIBRIDGE_TLS_SERVER_KEY=/certs/mcp-server-fetch-key.pem
    restart: always

  mcp-server-brave-search:
    volumes:
      - ../../certs:/certs
    env_file:
      - .env
    environment:
      - MINIBRIDGE_TLS_SERVER_CERT=/certs/mcp-server-brave-search-cert.pem
      - MINIBRIDGE_TLS_SERVER_KEY=/certs/mcp-server-brave-search-key.pem
    restart: always

  mcp-server-github:
    volumes:
      - ../../certs:/certs
    env_file:
      - .env
    environment:
      - MINIBRIDGE_TLS_SERVER_CERT=/certs/mcp-server-github-cert.pem
      - MINIBRIDGE_TLS_SERVER_KEY=/certs/mcp-server-github-key.pem
    restart: always

  mcp-server-sequential-thinking:
    volumes:
      - ../../certs:/certs
    env_file:
      - .env
    environment:
      - MINIBRIDGE_TLS_SERVER_CERT=/certs/mcp-server-sequential-thinking-cert.pem
      - MINIBRIDGE_TLS_SERVER_KEY=/certs/mcp-server-sequential-thinking-key.pem
    restart: always

  mcp-server-memory:
    volumes:
      - ../../certs:/certs
    env_file:
      - .env
    environment:
      - MINIBRIDGE_TLS_SERVER_CERT=/certs/mcp-server-memory-cert.pem
      - MINIBRIDGE_TLS_SERVER_KEY=/certs/mcp-server-memory-key.pem
    restart: always

  mcp-server-microsoft:
    volumes:
      - ../../certs:/certs
    env_file:
      - .env
    environment:
      - MINIBRIDGE_TLS_SERVER_CERT=/certs/mcp-server-microsoft-cert.pem
      - MINIBRIDGE_TLS_SERVER_KEY=/certs/mcp-server-microsoft-key.pem
    restart: always

volumes:
  postgres_data:
  memory_data:





