# yaml-language-server: $schema=/Users/marcusheese/src/acuvity/backend/pkgs/api/backend/jsonschema/import.json

label: demo-application-mcp-chatbot-demo

apps:
  - name: mcp-chatbot-demo
    description: "An example agentic demo application which uses MCP tools"
    selector:
      - - "@k8s:namespace=mcp-demo"
    subject:
      - - "@source:namespace=/"
        - "@source:name=app-tokens"
        - "@source:type=mtls"
        - "@apptoken:name=satyam-cluster-3"
    tracing: Recording
    otelReceivers:
      - endpoint: "127.0.0.1:4317"
        protocol: GRPC
      - endpoint: "127.0.0.1:4318"
        protocol: HTTP
    components:
      - name: ui
        description: "The UI running a react application."
        selector:
          - - "@k8s:label:app=mcp-demo-ui"
            - "@k8s:label:type=ui"
            - "@k8s:namespace=mcp-demo"
        egressMode: Inline
      - name: agent
        description: "The agent running the API server."
        selector:
          - - "@k8s:label:app=mcp-demo-agent"
            - "@k8s:label:type=mcp-client"
            - "@k8s:namespace=mcp-demo"
        egressMode: Inline
        providerName: mcp-demo-agent
        ingressProviderConfigs:
          - listenPort: 8000
            mode: Inline
            listenTLS: Disabled
            dialTLS: Disabled
      - name: mcp-brave-search
        description: "MCP Server: Brave Search"
        selector:
          - - "@k8s:label:app.kubernetes.io/name=mcp-server-brave-search"
            - "@k8s:label:app.kubernetes.io/component=mcp-server"
            - "@k8s:namespace=mcp-demo"
        providerName: mcp-demo-mcp-brave-search
        ingressProviderConfigs:
          - listenPort: 8000
            mode: Inline
            listenTLS: Disabled
            dialTLS: Disabled
        egressMode: Inline
      - name: mcp-fetch
        description: "MCP Server: Fetch"
        selector:
          - - "@k8s:label:app.kubernetes.io/name=mcp-server-fetch"
            - "@k8s:label:app.kubernetes.io/component=mcp-server"
            - "@k8s:namespace=mcp-demo"
        providerName: mcp-demo-mcp-fetch
        ingressProviderConfigs:
          - listenPort: 8000
            mode: Inline
            listenTLS: Disabled
            dialTLS: Disabled
        egressMode: Inline
      - name: mcp-github
        description: "MCP Server: GitHub"
        selector:
          - - "@k8s:label:app.kubernetes.io/name=mcp-server-github"
            - "@k8s:label:app.kubernetes.io/component=mcp-server"
            - "@k8s:namespace=mcp-demo"
        providerName: mcp-demo-mcp-github
        ingressProviderConfigs:
          - listenPort: 8000
            mode: Inline
            listenTLS: Disabled
            dialTLS: Disabled
        egressMode: Inline
      - name: mcp-memory
        description: "MCP Server: Memory"
        selector:
          - - "@k8s:label:app.kubernetes.io/name=mcp-server-memory"
            - "@k8s:label:app.kubernetes.io/component=mcp-server"
            - "@k8s:namespace=mcp-demo"
        providerName: mcp-demo-mcp-memory
        ingressProviderConfigs:
          - listenPort: 8000
            mode: Inline
            listenTLS: Disabled
            dialTLS: Disabled
        egressMode: Inline
      - name: mcp-sequential-thinking
        description: "MCP Server: Sequential Thinking"
        selector:
          - - "@k8s:label:app.kubernetes.io/name=mcp-server-sequential-thinking"
            - "@k8s:label:app.kubernetes.io/component=mcp-server"
            - "@k8s:namespace=mcp-demo"
        providerName: mcp-demo-mcp-sequential-thinking
        ingressProviderConfigs:
          - listenPort: 8000
            mode: Inline
            listenTLS: Disabled
            dialTLS: Disabled
        egressMode: Inline
      - name: mcp-everything
        description: "MCP Server: Everything"
        selector:
          - - "@k8s:label:app.kubernetes.io/name=mcp-server-everything"
            - "@k8s:label:app.kubernetes.io/component=mcp-server"
            - "@k8s:namespace=mcp-demo"
        providerName: mcp-demo-mcp-everything
        ingressProviderConfigs:
          - listenPort: 8000
            mode: Inline
            listenTLS: Disabled
            dialTLS: Disabled
        egressMode: Inline
      - name: mcp-microsoft
        description: "MCP Server: Microsoft"
        selector:
          - - "@k8s:label:app.kubernetes.io/name=mcp-server-microsoft"
            - "@k8s:label:app.kubernetes.io/component=mcp-server"
            - "@k8s:namespace=mcp-demo"
        providerName: mcp-demo-mcp-microsoft
        ingressProviderConfigs:
          - listenPort: 8000
            mode: Inline
            listenTLS: Disabled
            dialTLS: Disabled
        egressMode: Inline